# Generated by Django 3.0.1 on 2020-01-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desctription',
            new_name='description',
        ),
    ]
